boot:
  port: 8081
  # 缓存类型，local为本地缓存，redis为redis缓存
  cacheType: local
  # 前后端是否是一体化，true是一体，false是前后端分离
  frontCoupled: true
  profile: /home/boot/uploadPath
  mail:
    enabled: false
    #发送方  from 要和 username 一致, 否则报错
    from: aaaaa@qq.com
    # 邮件服务地址
    host: smtp.qq.com
    # 授权码 (设置 - 账户 - POP3/SMTP服务)
    password: aaaaaaa
    # QQ邮箱加密端口，不同邮箱的端口不一样
    port: 465
    to: aaaa@qq.com
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            trust: smtp.qq.com
          # 是否需要用户认证
          auth: true
          starttls:
            # 启用TLS加密
            enable: true
            required: true
  #需要忽略的路径
  saToken:
    excludeUrlPath:
      - /login
      - /logout
      - /register
      - /captchaImage
      - /*.html
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /favicon.ico
      - /static/**
      - /system/config/5
      - /profile/**
      - /common/download**
      - /common/download/resource**
      - /swagger-ui.html
      - /swagger-resources/**
      - /webjars/**
      - ${magic-api.web}/**
      - /magic-editor/**
      - /system/tenant/list**
      - /*/api-docs
      - /druid/**
      - /jmreport/**
      - /drag/**
      - /jimubi/**

# spring配置
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: boot..
        loginPassword: 123456..
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        # 配置连接超时时间
        connectTimeout: 30000
        # 配置网络超时时间
        socketTimeout: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        ## connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
        connectionProperties:
          druid:
            stat:
              mergeSql: true
              slowSqlMillis: 5000
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/boot-java?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: root2018


  # redis 配置
#  redis:
#    # 地址
#    host: 124.70.8.183
#    # 端口，默认为6379
#    port: 26379
#    # 数据库索引
#    database: 10
#    # 密码
#    password: ass_ssff22343_2222_12
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms

magic-api:
  #  配置web页面入口
  web: /magic/web
  resource:
    #  #配置文件存储位置。当以classpath开头时，为只读模式
    location: /data/magic-api